apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: myapp-deploy
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: myapp-deploy
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 30
