apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql2
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mysql2
  template:
    metadata:
      labels:
        name: mysql2
    spec:
      containers:
      - name: mysql2
        image: mysql:5728
        ports:
          - containerPort: 3306
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: "123aiadsd456"
