apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv001
  labels: 
    name: pv001
spec:
  nfs:
    path: /data/mysql/
    server: 192.168.1.148
  accessModes: ["ReadWriteMany","ReadWriteOnce"]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  capacity:
    storage: 5Gi
