apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deploy3

spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp3
  template:
    metadata:
      labels:
        app: myapp3
    spec:
      containers:
      - name: myapp3
        image: nginx:v01
        ports:
        - containerPort: 80
          name: http3

---
apiVersion: v1
kind: Service
metadata:
  name: myapp3
spec:
  selector:
    app: myapp3
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 80
  type: LoadBalancer
  
