apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - image: nginx:v01
        name: myapp
        ports:
        - containerPort: 80

        volumeMounts:
        - name: vnc-host-path
          mountPath: /var/log/nginx
      volumes:
      - name: vnc-host-path
        hostPath:
           path: /my/data

