
apiVersion: v1
kind: Service
metadata:
  name: my-deploy
spec:
  selector:
      app: myapp
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 30062
  type: NodePort

