apiVersion: v1
kind: Secret
metadata:
  name: mysql-pwd
data:
  mysql-jsj-pwd: MmdxZSVkcTAqXlRTYg==

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp3
  template:
    metadata:
      labels:
        app: myapp3
    spec:
      containers:
      - name: myapp3
        image: mysql:5728
        imagePullPolicy: Never
        env:
         - name: MYSQL_ROOT_PASSWORD
           valueFrom:
             secretKeyRef:
               name: mysql-pwd
               key: mysql-jsj-pwd
        ports:
        - name: http
          containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-demo
spec:
  type: NodePort
  ports: 
  - port: 3306
    nodePort: 30316
    targetPort: 3306
  selector:
    name: myapp3
