apiVersion: apps/v1
kind: Deployment
metadata:
  name: key-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: key-myapp
  template:
    metadata:
      labels:
        app: key-myapp
    spec:
      imagePullSecrets:
      - name: myregistrykeys
      containers:
      - name: key-myapp
        image: registry.cn-shenzhen.aliyuncs.com/jbjb/alpine:test-jar
        ports:
          - containerPort: 8080
     
---
apiVersion: v1
kind: Service
metadata:
  name: key-deploy
spec:
  selector:
      app: key-myapp
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  type: NodePort
