FROM alpine:latest
MAINTAINER jbjb@jb.com

# 换源
RUN echo 'http://mirrors.ustc.edu.cn/alpine/edge/main' > /etc/apk/repositories && \
     echo '@community http://mirrors.ustc.edu.cn/alpine/edge/community' >> /etc/apk/repositories  && \
     echo '@testing http://mirrors.ustc.edu.cn/alpine/edge/testing' >> /etc/apk/repositories   && \
     apk update

COPY  run.sh    /
RUN   chmod  +x  /run.sh
# 修正时区
ENV TIMEZONE Asia/Shanghai
RUN apk add tzdata bash-doc bash redis && \
    ln -snf /usr/share/zoneinfo/$TIMEZONE /etc/localtime && \
    echo $TIMEZONE > /etc/timezone && \
    sed -i 's/bind 127.0.0.1/bind redis-master/g'  /etc/redis.conf
    

ENTRYPOINT ["/run.sh"]
