
apiVersion: v1
kind: Endpoints
metadata:
  name: gfs
  namespace: default
subsets:
- addresses:
  - ip: 2.1.1.18
  - ip: 2.1.1.19
 
  ports:
  - port: 49152
    protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: gfs
  namespace: default
spec:
  ports:
  - port: 49152
    protocol: TCP
    targetPort: 49152
  sessionAffinity: None

