apiVersion: v1
kind: Service
metadata:
  name: external-service
spec:
  ports:
  - port: 80

---

kind: Endpoints
apiVersion: v1
metadata:
  name: external-service
 
subsets:
  - addresses:
      - ip: 10.10.10.182
    ports:
      - port: 90

