apiVersion: apps/v1
kind: Deployment
metadata:
  name: dog-jar-test
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dog-jar
      release: canary  
  template:	
    metadata:
      labels:
        app: dog-jar
        release: canary
    spec:
      containers:
      - name: dog-jar
        #image: alpine/jar-dog:v01 
        image: new-fish/war:v00
        imagePullPolicy: Never 
        ports:
        - name: http
          containerPort: 8080

