apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-jsj
spec:
  selector:
    matchLabels:
      app: my-jsj
  replicas: 1
  template:
    metadata:
      labels:
        app: my-jsj
    spec:
      containers:
      - name: my-jsj
        image: registry.cn-shenzhen.aliyuncs.com/jbjb/demon:dingding
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: myregistrykey
