apiVersion: v1
kind: Secret
metadata:
  name: myregistrykey
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJyZWdpc3RyeS5jbi1zaGVuemhlbi5hbGl5dW5jcy5jb20iOiB7CgkJCSJhdXRoIjogIjVyZXg1Wnl6NWE2ZDViNjM1TCtoNTZlUjVvcUE1cHl2NXB5SjZabVE1WVdzNVkrNE9tSXhNVFEwT0RZNE1ETkEiCgkJfQoJfSwKCSJIdHRwSGVhZGVycyI6IHsKCQkiVXNlci1BZ2VudCI6ICJEb2NrZXItQ2xpZW50LzE5LjAzLjggKGxpbnV4KSIKCX0KfQ== 
type: kubernetes.io/dockerconfigjson


