apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv001
  labels: 
    name: pv001
spec:
  nfs:
    path: /bbc
    server: 2.1.1.19
  accessModes: ["ReadWriteMany","ReadWriteOnce"]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  capacity:
    storage: 5Gi


---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv002
  labels: 
  name: pv002
spec:
  nfs:
    path: /bbc3
    server: 2.1.1.19
  accessModes: ["ReadWriteMany","ReadWriteOnce"]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs

  capacity:
    storage: 10Gi



