apiVersion: v1
kind: Service
metadata:
  name: redis-master
  labels:
    app: myapp-sts
spec:
  ports:
  - port: 6379
    name: web
  clusterIP: "None"
  selector:
    app: myapp-pod
    
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-master
  
spec:
  selector:
    matchLabels:
      app: myapp-pod
  serviceName: "redis"
  replicas: 1
  template:
    metadata:
      labels:
        app: myapp-pod
        
    spec:
      containers:
      - name: myapp
        image: redis-pvc:v01
        ports:
        - containerPort: 6379
          name: web
        volumeMounts:
        - name: myappdata
          mountPath: /data/redis
  volumeClaimTemplates:
  - metadata:
      name: myappdata
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: "nfs"
      resources:
        requests:
          storage: 2Gi
