apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv001
  labels: 
    name: pv001
spec:
  nfs:
    path: /data/bbc1
    server: 192.168.122.23
  accessModes: ["ReadWriteMany","ReadWriteOnce"]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  capacity:
    storage: 5Gi


---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv002
  labels: 
  name: pv002
spec:
  nfs:
    path: /data/bbc2
    server: 192.168.122.23
  accessModes: ["ReadWriteMany","ReadWriteOnce"]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs

  capacity:
    storage: 5Gi



